export const data = [
  {
    id: "1",
    name: "Juan",
    lastname: "Pérez",
    email: "juan@example.com",
  },
  {
    id: "2",
    name: "María",
    lastname: "García",
    email: "maria@example.com",
  },
  {
    id: "3",
    name: "Carlos",
    lastname: "López",
    email: "carlos@example.com",
  },
  {
    id: "4",
    name: "Ana",
    lastname: "Martínez",
    email: "ana@example.com",
  },
  {
    id: "5",
    name: "Pedro",
    lastname: "Rodríguez",
    email: "pedro@example.com",
  },
  {
    id: "6",
    name: "Laura",
    lastname: "Fernández",
    email: "laura@example.com",
  },
  {
    id: "7",
    name: "Miguel",
    lastname: "González",
    email: "miguel@example.com",
  },
  {
    id: "8",
    name: "Sofía",
    lastname: "López",
    email: "sofia@example.com",
  },
  {
    id: "9",
    name: "Diego",
    lastname: "Hernández",
    email: "diego@example.com",
  },
  {
    id: "10",
    name: "Lucía",
    lastname: "Díaz",
    email: "lucia@example.com",
  },
  {
    id: "11",
    name: "Andrés",
    lastname: "Torres",
    email: "andres@example.com",
  },
  {
    id: "12",
    name: "Carolina",
    lastname: "Ramírez",
    email: "carolina@example.com",
  },
  {
    id: "13",
    name: "Fernando",
    lastname: "Cruz",
    email: "fernando@example.com",
  },
  {
    id: "14",
    name: "Isabella",
    lastname: "Vargas",
    email: "isabella@example.com",
  },
  {
    id: "15",
    name: "Mateo",
    lastname: "Sánchez",
    email: "mateo@example.com",
  },
  {
    id: "16",
    name: "Valentina",
    lastname: "Luna",
    email: "valentina@example.com",
  },
  {
    id: "17",
    name: "Emilio",
    lastname: "Ortega",
    email: "emilio@example.com",
  },
  {
    id: "18",
    name: "Camila",
    lastname: "Rojas",
    email: "camila@example.com",
  },
  {
    id: "19",
    name: "Maximiliano",
    lastname: "Castillo",
    email: "maximiliano@example.com",
  },
  {
    id: "20",
    name: "Luis",
    lastname: "Gómez",
    email: "luis@example.com",
  },
];
